apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: munna
  labels:
    app: aws-cli
  annotations:
  
    eks.amazons.com/role-arn: arn:aws:iam::051725806636:role/s3-access-for-k8s
    #iam.amazonaws.com/role: arn:aws:iam::XXXXXXXXXXXX:role/my-s3-role
spec:
  containers:
  - image: brentley/awscli
    command:
      - "aws"
      - "s3"
      - "ls"
    name: aws-cli
  serviceAccountName: irsa-service-account  
